INSERT INTO `actividadesgsst` (`NombreActividad`, `Capitulo`) VALUES

-- CAPÍTULO 1: Empresas con 10 o menos trabajadores, riesgo I, II o III
('Asignación de persona que diseña el Sistema de Gestión de SST', 'uno'),
('Afiliación al Sistema de Seguridad Social Integral', 'uno'),
('Capacitación en SST', 'uno'),
('Plan Anual de Trabajo', 'uno'),
('Evaluaciones médicas ocupacionales', 'uno'),
('Identificación de peligros; evaluación y valoración de riesgos', 'uno'),
('Medidas de prevención y control frente a peligros/riesgos identificados', 'uno'),

-- CAPÍTULO 2: Empresas de 11 a 50 trabajadores, riesgo I, II o III
('Asignación de una persona que diseñe el Sistema de Gestión de SST', 'dos'),
('Asignación de recursos para el Sistema de Gestión de SST', 'dos'),
('Afiliación al Sistema de Seguridad Social Integral', 'dos'),
('Conformación y funcionamiento del COPASST', 'dos'),
('Conformación y funcionamiento del Comité de Convivencia Laboral', 'dos'),
('Programa de capacitación', 'dos'),
('Política de Seguridad y Salud en el Trabajo', 'dos'),
('Plan Anual de Trabajo', 'dos'),
('Archivo y retención documental del Sistema de Gestión de SST', 'dos'),
('Descripción socio demográfica y Diagnóstico de condiciones de salud', 'dos'),
('Actividades de medicina del trabajo y de prevención y promoción de la salud', 'dos'),
('Evaluaciones médicas ocupacionales', 'dos'),
('Restricciones y recomendaciones médicas laborales', 'dos'),
('Reporte de accidentes de trabajo y enfermedades laborales', 'dos'),
('Investigación de incidentes, accidentes de trabajo y enfermedades cuando sean diagnosticadas como laborales', 'dos'),
('Identificación de peligros y evaluación y valoración de riesgos', 'dos'),
('Mantenimiento periódico de instalaciones, equipos, máquinas y herramientas', 'dos'),
('Entrega de los elementos de protección personal EPP y capacitación en uso adecuado', 'dos'),
('Plan de prevención, preparación y respuesta ante emergencias', 'dos'),
('Brigada de prevención, preparación y respuesta ante emergencias', 'dos'),
('Revisión por la alta dirección', 'dos'),

-- CAPÍTULO 3: Empresas de más de 50 trabajadores o de 50 o menos con riesgo IV o V
('Asignación de una persona que diseñe e implemente el Sistema de Gestión de SST', 'tres'),
('Asignación de responsabilidades en SST', 'tres'),
('Asignación de recursos para el Sistema de Gestión en SST', 'tres'),
('Afiliación al Sistema de Seguridad Social Integral', 'tres'),
('Identificación de trabajadores que se dediquen en forma permanente a actividades de alto riesgo y cotización de pensión especial', 'tres'),
('Conformación y funcionamiento del COPASST', 'tres'),
('Capacitación de los integrantes del COPASST', 'tres'),
('Conformación y funcionamiento del Comité de Convivencia Laboral', 'tres'),
('Programa de capacitación anual', 'tres'),
('Inducción y reinducción en SST', 'tres'),
('Curso Virtual de capacitación de cincuenta (50) horas en SST', 'tres'),
('Política de Seguridad y Salud en el Trabajo', 'tres'),
('Objetivos de SST', 'tres'),
('Evaluación Inicial del Sistema de Gestión', 'tres'),
('Plan Anual de Trabajo', 'tres'),
('Archivo y retención documental del Sistema de Gestión de SST', 'tres'),
('Rendición de cuentas', 'tres'),
('Matriz legal', 'tres'),
('Mecanismos de comunicación', 'tres'),
('Identificación y evaluación para la adquisición de bienes y servicios', 'tres'),
('Evaluación y selección de proveedores y contratistas', 'tres'),
('Gestión del cambio', 'tres'),
('Descripción sociodemográfica y Diagnóstico de condiciones de salud de los trabajadores', 'tres'),
('Actividades de medicina del trabajo y de prevención y promoción de la Salud', 'tres'),
('Perfiles de cargos', 'tres'),
('Evaluaciones médicas ocupacionales', 'tres'),
('Custodia de las historias clínicas', 'tres'),
('Restricciones y recomendaciones médico laborales', 'tres'),
('Estilos de vida y entorno saludable', 'tres'),
('Servicios de higiene', 'tres'),
('Manejo de Residuos', 'tres'),
('Reporte de accidentes de trabajo y enfermedades laborales', 'tres'),
('Investigación de incidentes, accidentes de trabajo y las enfermedades cuando sean diagnosticadas como laborales', 'tres'),
('Registro y análisis estadístico de accidentes de trabajo y enfermedades laborales', 'tres'),
('Frecuencia de accidentalidad', 'tres'),
('Severidad de accidentalidad', 'tres'),
('Proporción de accidentes de trabajo mortales', 'tres'),
('Prevalencia de la enfermedad laboral', 'tres'),
('Incidencia de la enfermedad laboral', 'tres'),
('Ausentismo por causa médica', 'tres'),
('Metodología para identificación de peligros, evaluación y valoración de riesgos', 'tres'),
('Identificación de peligros y evaluación y valoración de riesgos con participación de todos los niveles de la empresa', 'tres'),
('Identificación de sustancias catalogadas como carcinógenas o con toxicidad aguda', 'tres'),
('Mediciones ambientales', 'tres'),
('Medidas de prevención y control frente a peligros/riesgos identificados', 'tres'),
('Aplicación de medidas de prevención y control por parte de los trabajadores', 'tres'),
('Procedimientos e instructivos internos de seguridad y salud en el trabajo', 'tres'),
('Inspecciones a instalaciones, maquinaria o equipos', 'tres'),
('Mantenimiento periódico de las instalaciones, equipos, máquinas y herramientas', 'tres'),
('Entrega de los Elementos de Protección Personal EPP y capacitación en uso adecuado', 'tres'),
('Plan de prevención, preparación y respuesta ante emergencias', 'tres'),
('Brigada de prevención, preparación y respuesta ante emergencias', 'tres'),
('Definición de indicadores del Sistema de Gestión de Seguridad y Salud en el Trabajo', 'tres'),
('Auditoría anual', 'tres'),
('Revisión por la alta dirección. Alcance de la auditoría del Sistema de Gestión', 'tres'),
('Planificación de la auditoría con el COPASST', 'tres'),
('Acciones preventivas y/o correctivas', 'tres'),
('Acciones de mejora conforme a revisión de la Alta Dirección', 'tres'),
('Acciones de mejora con base en investigaciones de accidentes de trabajo y enfermedades laborales', 'tres'),
('Plan de mejoramiento', 'tres');